# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWDJzFj975f4HCFMzH3Oj6aLzSaZSJDE
"""

# ============================================================
# HUMAN RESOURCES ANALYTICS DASHBOARD
# Internship Task 2
# Single Code for Google Colab / Google AI Studio
# ============================================================

# Install libraries
!pip -q install pandas numpy plotly scikit-learn openpyxl

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

np.random.seed(42)
random.seed(42)

print("="*60)
print("HUMAN RESOURCES ANALYTICS")
print("="*60)

# ============================================================
# CREATE SAMPLE EMPLOYEE DATA
# ============================================================

n = 600

departments = [
    "HR",
    "IT",
    "Finance",
    "Marketing",
    "Sales",
    "Operations",
    "Support"
]

education = [
    "Bachelor",
    "Master",
    "Diploma",
    "MBA"
]

employees = pd.DataFrame({
    "EmployeeID": range(1001,1001+n),
    "Department": np.random.choice(departments,n),
    "Age": np.random.randint(22,60,n),
    "Experience": np.random.randint(0,30,n),
    "Education": np.random.choice(education,n),
    "PerformanceScore": np.random.randint(60,100,n),
    "SatisfactionScore": np.random.randint(40,100,n),
    "RecruitmentDays": np.random.randint(10,90,n),
    "Salary": np.random.randint(25000,120000,n),
    "TrainingHours": np.random.randint(5,100,n)
})

employees["Attrition"] = np.where(
    employees["SatisfactionScore"]<60,
    np.random.choice(["Yes","No"],n,p=[0.45,0.55]),
    np.random.choice(["Yes","No"],n,p=[0.08,0.92])
)

# ============================================================
# KPI CALCULATIONS
# ============================================================

total_emp = len(employees)

active_emp = len(employees[employees["Attrition"]=="No"])

left_emp = len(employees[employees["Attrition"]=="Yes"])

turnover_rate = round((left_emp/total_emp)*100,2)

avg_recruit = round(employees["RecruitmentDays"].mean(),2)

avg_sat = round(employees["SatisfactionScore"].mean(),2)

avg_perf = round(employees["PerformanceScore"].mean(),2)

print("\n------------ HR KPIs ------------")

print("Total Employees :", total_emp)

print("Active Employees:", active_emp)

print("Employees Left  :", left_emp)

print("Turnover Rate   :", turnover_rate,"%")

print("Average Recruitment Time :",avg_recruit,"days")

print("Average Satisfaction :",avg_sat)

print("Average Performance :",avg_perf)

# ============================================================
# DEPARTMENT SUMMARY
# ============================================================

dept_summary = employees.groupby("Department").agg(
Employees=("EmployeeID","count"),
AverageSalary=("Salary","mean"),
AveragePerformance=("PerformanceScore","mean"),
AverageSatisfaction=("SatisfactionScore","mean")
).reset_index()

print("\nDepartment Summary")
print(dept_summary)

# ============================================================
# RECRUITMENT METRICS
# ============================================================

fig = px.bar(
    dept_summary,
    x="Department",
    y="Employees",
    title="Employees by Department"
)

fig.show()

fig = px.box(
    employees,
    x="Department",
    y="RecruitmentDays",
    title="Recruitment Time by Department"
)

fig.show()

# ============================================================
# TURNOVER ANALYSIS
# ============================================================

attrition = employees["Attrition"].value_counts().reset_index()

attrition.columns=["Status","Count"]

fig = px.pie(
    attrition,
    names="Status",
    values="Count",
    title="Employee Turnover"
)

fig.show()

# ============================================================
# SATISFACTION ANALYSIS
# ============================================================

fig = px.histogram(
    employees,
    x="SatisfactionScore",
    nbins=20,
    title="Employee Satisfaction Distribution"
)

fig.show()

# ============================================================
# PERFORMANCE ANALYSIS
# ============================================================

fig = px.scatter(
    employees,
    x="Experience",
    y="PerformanceScore",
    color="Department",
    title="Experience vs Performance"
)

fig.show()

# ============================================================
# TRAIN MACHINE LEARNING MODEL
# Predict Hiring Requirement
# ============================================================

monthly_data = pd.DataFrame({
    "Month": np.arange(1,25),
    "Recruitment": np.random.randint(10,70,24),
    "Attrition": np.random.randint(5,30,24),
    "BusinessGrowth": np.random.randint(1,20,24)
})

monthly_data["HiringNeeded"] = (
monthly_data["Recruitment"]*0.6 +
monthly_data["Attrition"]*1.8 +
monthly_data["BusinessGrowth"]*2 +
np.random.randint(-5,5,24)
)

X = monthly_data[[
    "Recruitment",
    "Attrition",
    "BusinessGrowth"
]]

y = monthly_data["HiringNeeded"]

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

model=RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train,y_train)

pred=model.predict(X_test)

print("\nMachine Learning MAE:",
round(mean_absolute_error(y_test,pred),2))

future=pd.DataFrame({
"Recruitment":[40],
"Attrition":[18],
"BusinessGrowth":[12]
})

future_prediction=model.predict(future)[0]

print("\nForecast Hiring Requirement :",round(future_prediction),"Employees")

# ============================================================
# FUTURE FORECAST CHART
# ============================================================

forecast=pd.DataFrame({
"Metric":["Predicted Hiring"],
"Employees":[round(future_prediction)]
})

fig=px.bar(
forecast,
x="Metric",
y="Employees",
title="Predicted Hiring Requirement"
)

fig.show()

# ============================================================
# EXPORT CSV FOR POWER BI
# ============================================================

employees.to_csv("HR_Employees.csv",index=False)

dept_summary.to_csv("Department_Summary.csv",index=False)

monthly_data.to_csv("Hiring_Forecast.csv",index=False)

print("\nCSV Files Saved Successfully!")

print("""
Generated Files:
1. HR_Employees.csv
2. Department_Summary.csv
3. Hiring_Forecast.csv
""")

# ============================================================
# POWER BI DASHBOARD SUGGESTIONS
# ============================================================

print("="*60)
print("POWER BI DASHBOARD")
print("="*60)

print("""
KPI Cards
---------
• Total Employees
• Active Employees
• Turnover Rate
• Average Recruitment Time
• Average Satisfaction
• Average Performance

Charts
------
• Employee Count by Department
• Attrition Pie Chart
• Recruitment Time by Department
• Satisfaction Distribution
• Performance vs Experience
• Hiring Forecast

Slicers
--------
Department
Education
Attrition
Age

Machine Learning
----------------
Predicted Hiring Requirement
""")