# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-yvH1Dd216kcAYkHgXW12tetzI9-vm0
"""

# ==========================
# Financial Health Dashboard
# ==========================

# Install required libraries (Run once)
!pip -q install plotly pandas scikit-learn

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.linear_model import LinearRegression

# -----------------------------
# Sample Financial Data
# -----------------------------
data = {
    "Year":[2019,2020,2021,2022,2023,2024],
    "Revenue":[500000,540000,610000,690000,760000,850000],
    "Expenses":[350000,370000,410000,450000,500000,550000],
    "Assets":[900000,950000,1000000,1100000,1200000,1300000],
    "Liabilities":[400000,420000,430000,450000,470000,500000],
    "CashFlow":[80000,90000,105000,120000,140000,160000]
}

df = pd.DataFrame(data)

# -----------------------------
# Financial Calculations
# -----------------------------
df["Profit"] = df["Revenue"] - df["Expenses"]
df["Profit Margin (%)"] = (df["Profit"]/df["Revenue"])*100
df["Equity"] = df["Assets"] - df["Liabilities"]
df["Current Ratio"] = df["Assets"]/df["Liabilities"]
df["Debt Ratio"] = df["Liabilities"]/df["Assets"]

# -----------------------------
# Forecast Function
# -----------------------------
future_years = np.array([2025,2026,2027]).reshape(-1,1)
X = df["Year"].values.reshape(-1,1)

def forecast(column):
    model = LinearRegression()
    model.fit(X, df[column])
    return model.predict(future_years)

forecast_revenue = forecast("Revenue")
forecast_expenses = forecast("Expenses")
forecast_profit = forecast("Profit")

forecast_df = pd.DataFrame({
    "Year":[2025,2026,2027],
    "Revenue":forecast_revenue,
    "Expenses":forecast_expenses,
    "Profit":forecast_profit
})

# -----------------------------
# Dashboard
# -----------------------------
fig = make_subplots(
    rows=3, cols=2,
    subplot_titles=(
        "Income Statement",
        "Balance Sheet",
        "Cash Flow",
        "Profit Margin",
        "Revenue Forecast",
        "Financial Ratios"
    )
)

# Income Statement
fig.add_trace(go.Bar(x=df["Year"], y=df["Revenue"], name="Revenue"), row=1,col=1)
fig.add_trace(go.Bar(x=df["Year"], y=df["Expenses"], name="Expenses"), row=1,col=1)
fig.add_trace(go.Scatter(x=df["Year"], y=df["Profit"], mode="lines+markers", name="Profit"), row=1,col=1)

# Balance Sheet
fig.add_trace(go.Bar(x=df["Year"], y=df["Assets"], name="Assets"), row=1,col=2)
fig.add_trace(go.Bar(x=df["Year"], y=df["Liabilities"], name="Liabilities"), row=1,col=2)
fig.add_trace(go.Scatter(x=df["Year"], y=df["Equity"], mode="lines+markers", name="Equity"), row=1,col=2)

# Cash Flow
fig.add_trace(go.Scatter(x=df["Year"], y=df["CashFlow"], mode="lines+markers", name="Cash Flow"), row=2,col=1)

# Profit Margin
fig.add_trace(go.Scatter(
    x=df["Year"],
    y=df["Profit Margin (%)"],
    mode="lines+markers",
    name="Profit Margin"
), row=2,col=2)

# Forecast
fig.add_trace(go.Scatter(
    x=df["Year"],
    y=df["Revenue"],
    mode="lines+markers",
    name="Revenue"
), row=3,col=1)

fig.add_trace(go.Scatter(
    x=forecast_df["Year"],
    y=forecast_df["Revenue"],
    mode="lines+markers",
    line=dict(dash="dash"),
    name="Forecast Revenue"
), row=3,col=1)

fig.add_trace(go.Scatter(
    x=forecast_df["Year"],
    y=forecast_df["Profit"],
    mode="lines+markers",
    line=dict(dash="dot"),
    name="Forecast Profit"
), row=3,col=1)

# Financial Ratios
fig.add_trace(go.Scatter(
    x=df["Year"],
    y=df["Current Ratio"],
    mode="lines+markers",
    name="Current Ratio"
), row=3,col=2)

fig.add_trace(go.Scatter(
    x=df["Year"],
    y=df["Debt Ratio"],
    mode="lines+markers",
    name="Debt Ratio"
), row=3,col=2)

fig.update_layout(
    height=1000,
    width=1200,
    title="Financial Health Dashboard",
    template="plotly_dark"
)

fig.show()

# -----------------------------
# Financial Summary
# -----------------------------
print("\n========== Financial Summary ==========")
print(df)

print("\n========== Forecast ==========")
print(forecast_df)

print("\n========== Actionable Insights ==========")

if df["Profit"].iloc[-1] > df["Profit"].iloc[-2]:
    print("✔ Profit is increasing.")
else:
    print("⚠ Profit is decreasing.")

if df["Debt Ratio"].iloc[-1] < 0.5:
    print("✔ Debt level is healthy.")
else:
    print("⚠ High debt level detected.")

if df["Current Ratio"].iloc[-1] > 1.5:
    print("✔ Liquidity position is strong.")
else:
    print("⚠ Improve current assets to strengthen liquidity.")

print("✔ Forecast suggests future revenue and profit trends for budgeting and planning.")